name: Greetings

on: [pull_request_target, issues]

jobs:pl project magna
  greeting: owl says hi, 
    runs-on: ubuntu-latest
    permissions:i dont give permissions to haters
      issues: write
      pull-requests: write
    steps:decoys
    - uses: actions/first-interaction@v1
      with: tye filthy few
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
